[2023-09-07T07:39:46.192+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_ingestion_dag.ingest scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-09-07T07:39:46.197+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_ingestion_dag.ingest scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-09-07T07:39:46.197+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-09-07T07:39:46.204+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ingest> on 2023-07-01 00:00:00+00:00
[2023-09-07T07:39:46.209+0000] {standard_task_runner.py:57} INFO - Started process 104 to run task
[2023-09-07T07:39:46.212+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'local_ingestion_dag', 'ingest', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_localdb_dag.py', '--cfg-path', '/tmp/tmpjxuxj81u']
[2023-09-07T07:39:46.215+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask ingest
[2023-09-07T07:39:46.255+0000] {task_command.py:415} INFO - Running <TaskInstance: local_ingestion_dag.ingest scheduled__2023-07-01T00:00:00+00:00 [running]> on host 3ebe1114701d
[2023-09-07T07:39:46.290+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-07T07:39:46.470+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-01T00:00:00+00:00'
[2023-09-07T07:39:46.471+0000] {logging_mixin.py:151} INFO - yellow_taxi_2023_07 /opt/***/output_2023-07.parquet 2023-07
[2023-09-07T07:39:46.486+0000] {logging_mixin.py:151} INFO - connection established successfully, inserting data...
[2023-09-07T07:39:46.540+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 18, in ingest_callable
    df = pd.read_parquet(parquet_file)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parquet.py", line 227, in read
    pa_table = self.api.parquet.read_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 2926, in read_table
    dataset = _ParquetDatasetV2(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 2466, in __init__
    [fragment], schema=schema or fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 1004, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
[2023-09-07T07:39:46.551+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=local_ingestion_dag, task_id=ingest, execution_date=20230701T000000, start_date=20230907T073946, end_date=20230907T073946
[2023-09-07T07:39:46.561+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 81 for task ingest (Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.; 104)
[2023-09-07T07:39:46.586+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-07T07:39:46.604+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
