[2023-09-06T15:25:18.877+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_ingestion_dag.ingest scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-09-06T15:25:18.883+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_ingestion_dag.ingest scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-09-06T15:25:18.884+0000] {taskinstance.py:1361} INFO - Starting attempt 12 of 12
[2023-09-06T15:25:18.892+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): ingest> on 2023-01-01 00:00:00+00:00
[2023-09-06T15:25:18.897+0000] {standard_task_runner.py:57} INFO - Started process 387 to run task
[2023-09-06T15:25:18.900+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'local_ingestion_dag', 'ingest', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_localdb_dag.py', '--cfg-path', '/tmp/tmpckbi8cxy']
[2023-09-06T15:25:18.904+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask ingest
[2023-09-06T15:25:18.953+0000] {task_command.py:415} INFO - Running <TaskInstance: local_ingestion_dag.ingest scheduled__2023-01-01T00:00:00+00:00 [running]> on host 8c255a8714b1
[2023-09-06T15:25:19.000+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-09-06T15:25:19.308+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_ingestion_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2023-09-06T15:25:19.309+0000] {logging_mixin.py:151} INFO - yellow_taxi_2023_01 /opt/***/output_2023-01.csv 2023-01
[2023-09-06T15:25:19.324+0000] {logging_mixin.py:151} INFO - connection established successfully, inserting data...
[2023-09-06T15:25:19.325+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 18, in ingest_callable
    df_iter = pd.read_csv(csv_file, iterator=True, chunksize=100000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2023-01.csv'
[2023-09-06T15:25:19.335+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=local_ingestion_dag, task_id=ingest, execution_date=20230101T000000, start_date=20230906T152518, end_date=20230906T152519
[2023-09-06T15:25:19.344+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task ingest ([Errno 2] No such file or directory: '/opt/airflow/output_2023-01.csv'; 387)
[2023-09-06T15:25:19.396+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-06T15:25:19.414+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
